dist: build/dist

builds:
  - main: .
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags: "-s -w -X main.version={{ .Version }}"
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  skip: false