name: Chocolatey deploy

on:
  release:
    types: [created]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Build the CLI
        run: |
          cd cmd/gsc
          go build -o go-spotify-cli.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: go-spotify-cli
          path: cmd/gsc/go-spotify-cli.exe
  Package-and-Push:
    needs: build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: go-spotify-cli
          path: .
      - name: Extract Version
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
      - name: Update Nuspec File
        run: |
          $version = "${{ env.VERSION }}"
          $nuspecPath = "go-spotify-cli.nuspec"
          [xml]$nuspec = Get-Content $nuspecPath
          $ns = New-Object System.Xml.XmlNamespaceManager($nuspec.NameTable)
          $ns.AddNamespace("ns", "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd")
          $nuspec.SelectSingleNode("//ns:package/ns:metadata/ns:version", $ns).InnerText = $version
          $nuspec.Save($nuspecPath)
          Get-Content $nuspecPath # Debugging: Print out the updated nuspec file
      - name: Pack Chocolatey Package
        run: choco pack
      - name: Push to Chocolatey
        run: |
          choco push your-package-name.nupkg --api-key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'envoy49'
          git config --global user.email 'hasan.alv@outlook.com'
          git add go-spotify-cli.nuspec
          git commit -m "Update .nuspec file for release ${{ env.VERSION }}"
          git push
