name: Chocolatey deploy

on:
  release:
    types: [created]

jobs:
  Build:
    runs-on: windows-latest
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Extract Tag Name from Release
        id: extract_version
        run: |
          echo "::set-output name=version::${{ github.event.release.tag_name }}"
          echo "Extracted tag: ${{ github.event.release.tag_name }}"
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21'
      - name: Build the CLI
        run: |
          cd cmd/gsc
          go build -o go-spotify-cli.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: go-spotify-cli
          path: cmd/gsc/go-spotify-cli.exe

  Package-and-Push:
    needs: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: go-spotify-cli
          path: .
      - name: Update Nuspec File
        run: |
          $version = "${{ needs.Build.outputs.version }}"
          $nuspecPath = "go-spotify-cli.nuspec"
          [xml]$nuspec = Get-Content $nuspecPath
          $ns = New-Object System.Xml.XmlNamespaceManager($nuspec.NameTable)
          $ns.AddNamespace("ns", "http://schemas.microsoft.com/packaging/2015/06/nuspec.xsd")
          $versionNode = $nuspec.SelectSingleNode("//ns:metadata/ns:version", $ns)
          $versionNode.InnerText = $version
          $nuspec.Save($nuspecPath)
          cat $nuspecPath # For debugging: print the contents of the nuspec file to check if version is updated.
      - name: Pack Chocolatey Package
        run: |
          choco pack go-spotify-cli.nuspec
      - name: Push to Chocolatey
        run: |
          choco push go-spotify-cli.*.nupkg --api-key ${{ secrets.CHOCOLATEY_API_KEY }} --source https://push.chocolatey.org/
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'envoy49'
          git config --global user.email 'hasan.alv@outlook.com'
          git add go-spotify-cli.nuspec
          git commit -m "Update .nuspec file for release ${{ needs.Build.outputs.version }}"
          git push
