name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  artifacts:
    # This job references a reusable workflow for handling artifacts.
    uses: ./.github/workflows/artifacts.yml
    with:
      publish: true
      release: true
    permissions:
      contents: write
      packages: write
      id-token: write
      security-events: write

  call-homebrew-workflow:
    # This job references another reusable workflow for the Homebrew update.
    # It starts only after the 'artifacts' job has completed successfully.
    needs: artifacts
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    uses: ./.github/workflows/homebrew.yml
    with:
      tag_name: ${{ github.ref_name }}
    secrets: inherit
